// <auto-generated/>
#pragma warning disable

using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System;
using System.Text;
using arr = Microsoft.Azure.RemoteRendering;
using ManagerId = System.UInt16;

public class RRInterface
{
    [DllImport("RemoteRenderingClient", CallingConvention = CallingConvention.Cdecl)]
    public static extern arr.Result RemoteRendering_Startup([MarshalAs(UnmanagedType.Struct), In] ref arr.RemoteRenderingInitialization init);
    [DllImport("RemoteRenderingClient", CallingConvention = CallingConvention.Cdecl)]
    public static extern arr.Result RemoteRendering_Shutdown();

    [DllImport("RemoteRenderingClient", CallingConvention = CallingConvention.Cdecl)]
    public static extern void RemoteManager_Update(ManagerId managerId);
  
    [DllImport("RemoteRenderingClient", CallingConvention = CallingConvention.Cdecl)]
    public static extern arr.Result RemoteRendering_SetConnectionGameEngine(Int64 engineIdentifier);
}
